import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import React from 'react'
import { Index } from '../components/template/Index'
import { useAuthorPosts } from '../hooks/authorPosts'
import { useGetCategories } from '../hooks/categories'
import { useGetPosts } from '../hooks/posts'

export default function Home() {
  const posts = useGetPosts()
  const categories = useGetCategories()
  const authors = useAuthorPosts()
  const selects = {
    options: [{ text: 'Latest' }, { text: 'Last Week' }],
    name: 'sort-post',
  }
  const router = useRouter()
  const currentPage = Number(router.query.page) || 1
  const pagination = { length: 5, to: '?page', current: currentPage }
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index
        authorPosts={{ authors: authors }}
        pagination={pagination}
        categories={categories}
        posts={posts}
        selects={selects}
      />
    </React.Fragment>
  )
}
